# set theme
import = [
    "C:/code/scripts/alacritty/themes/themes/campbell.toml"
]

[window]
	#decorations = "None"
	decorations_theme_variant = "Dark"
	startup_mode = "Maximized"
	title = "alacritty"
	dynamic_title = false
	
	
[selection]
	save_to_clipboard = true
	
	
[keyboard]

#fix Control-* hotkeys behaviour
bindings = [
{key = "Key6",     mods = "Control", chars = "\u001e"},
{key = "Space",    mods = "Control", chars = "\u0000"},
]

[mouse]
bindings = [
{mouse = "Right", mods = "Shift", action = "Paste" },
]

	
[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold   = {style = "Regular"}
size = 12